name: Create Branch on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'rwagner00/search_api_pantheon' }}
    env:
      BRANCH: ${{ github.ref_name }}
      WORKSPACE: ${{ github.workspace }}
      DRUPAL_ORG_REMOTE: ${{ secrets.DRUPAL_ORG_REMOTE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract tag name
        id: tag_name
        run: |
          FULL_TAG=${GITHUB_REF#refs/tags/}
          MAJOR_MINOR=$(echo $FULL_TAG | cut -d '.' -f 1,2)
          echo "::set-output name=BRANCH_NAME::$MAJOR_MINOR"
      - name: Print Branch Name
        id: print_branch_name
        run: |
          echo "findme"
          echo ${{ steps.tag_name.outputs.BRANCH_NAME }}
          echo "endfindme"
      - name: Check if branch exists
        id: check_branch
        run: |
          if git ls-remote --heads origin ${{ steps.tag_name.outputs.BRANCH_NAME }}; then
            echo "Branch for tag already exists."
            echo "::set-output name=exists::true"
          else
            echo "Branch for tag does not exist."
            echo "::set-output name=exists::false"
          fi
      - name: Create branch
        if: steps.check_branch.outputs.exists == 'false'
        run: |
          git checkout -b ${{ steps.tag_name.outputs.BRANCH_NAME }}
          git push origin ${{ steps.tag_name.outputs.BRANCH_NAME }}

      - name: Merge changes from current default branch
        if: steps.check_branch.outputs.exists == 'true'
        run: |
          git fetch
          git checkout -b origin/${{ steps.tag_name.outputs.BRANCH_NAME }}
          git merge origin/${{ github.event.repository.default_branch }}
          git push origin ${{ steps.tag_name.outputs.BRANCH_NAME }}

